### ISSUE TITLE
Error calling mq.close_channel()

### ISSUE THREAD

**Issue by germainc** [perfectsquircle/pg_mq#7]
Calling mq.close_channel() returns an error:
` mq.close_channel(bigint) is a procedure (SQLSTATE 42809)`

Looks like `EXECUTE mq.close_channel(current_channel_id);` in that procedure should be `CALL mq.close_channel(current_channel_id);`

**Comment by perfectsquircle** [comment]
Curiously I had this fixed locally, but forgot to push it. Thanks for catching this.
